# application-dev.properties
spring.application.name=hrms-dev

#spring.datasource.url=jdbc:postgresql://localhost:5432/trial_hrms
# spring.datasource.url=jdbc:postgresql://localhost:5432/backupDb1

# spring.datasource.username=postgres
# spring.datasource.password=postgres

spring.datasource.url=jdbc:postgresql://localhost:5432/backupdb1
spring.datasource.username=shivam
spring.datasource.password=shivam123

server.port=8181

# JWT credentials
app.jwt-secret= ======================BezKoder=Spring===========================
app.jwt-expiration-milliseconds=86400000

user.image.upload.path=D://AVINASH_WS//HRMS_SERVER//prodResources//user//
Staff.image.upload.path=D://AVINASH_WS//HRMS_SERVER//prodResources//staff//
staff_doc.image.upload.path=D://AVINASH_WS//HRMS_SERVER//prodResources//staff_doc//
other_doc.image.upload.path=D://AVINASH_WS//HRMS_SERVER//prodResources//other_doc//

