# application.properties
spring.profiles.active=dev
#prod
# Enable debug logging for Spring Security
logging.level.org.springframework.security=DEBUG

# Hibernate Settings
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

#Defalut file size accected by server
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

#to generate ssl
