# application-prod.properties
spring.application.name=hrms-prod

spring.datasource.url=jdbc:postgresql://3.144.4.209:5432/trial_hrms
#spring.datasource.url=jdbc:postgresql://192.168.1.35:5432/trial_hrms
spring.datasource.username=postgres
spring.datasource.password=newpassword@Uinfo2024

server.port=8181

# JWT credentials
app.jwt-secret=prod==XXXXXXXXXXXXXXXX======SURAJ==XXXXXXXXXXXXXXXXXOOOOOOOO=secret
app.jwt-expiration-milliseconds=86400000

#ssl configurations part

server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=spshrms@123
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=springboot



user.image.upload.path=/home/ubuntu/backend_ws/prodResources/user/
staff.image.upload.path=/home/ubuntu/backend_ws/prodResources/staff/
staff_doc.image.upload.path=/home/ubuntu/backend_ws/prodResources/staff_doc/
other_doc.image.upload.path=/home/ubuntu/backend_ws/prodResources/other_doc/
